### ISSUE TITLE
Use Font Awesome icons

### ISSUE THREAD

**Issue by cmb69** [cmb69/pagemanager_xh#27]
If cmsimple-xh/cmsimple-xh#168 will be accepted, it would make sense to use Font Awesome icons in Pagemanager_XH.

See also https://cmsimpleforum.com/viewtopic.php?t=12587&p=58759#p58743.

**Comment by cmb69** [comment]
And see https://cmsimpleforum.com/viewtopic.php?f=16&t=12587&start=60#p59455.

**Comment by cmb69** [comment]
@frase-git Gut so?

**Comment by frase-git** [comment]
> Gut so?

Ich hoffe. ;-)
Testen kann ich erst viel später.
