### ISSUE TITLE
Pages with special HTML characters are not properly handled

### ISSUE THREAD

**Issue by cmb69** [cmb69/pagemanager_xh#33]
Steps to reproduce:
* add a page "`me & you`"
* save

Now the page is titled "`me &amp; you`".

**Comment by frase-git** [comment]
after saving the page is titled: `me &amp; you`
click on "rename", the title is: `me &amp;amp; you`

**Comment by cmb69** [comment]
See also https://cmsimpleforum.com/viewtopic.php?f=16&t=12587&start=60#p59453.
