### ISSUE TITLE
Unpublished pages get "EMPTY HEADING"

### ISSUE THREAD

**Issue by frase-git** [cmb69/pagemanager_xh#53]
(Version 3.0beta3: hoffentlich nicht schon gemeldet)

Werden Seiten über Pagedata "unveröffentlicht" geschaltet, erhalten Sie im Pagemanager das Label:
"LEERE ÜBERSCHRIFT".

BTW: Wenn "unveröffentlicht", dann sollte auch automatisch "In der Navigation anzeigen? = AUS" geschaltet werden.

**Comment by cmb69** [comment]
Stimmt. Das liegt daran, dass der Pagemanager die Seitendaten fälschlicherweise im Ansichtsmodus anfragt; um diesen Fehler zu beheben, müsste nur [diese Zeile](https://github.com/cmb69/pagemanager_xh/blob/3.0beta3/classes/MainAdminController.php#L172) geändert werden zu:
````
                ->with('action', 'plugin_data')->with('edit', '')
````
> BTW: Wenn "unveröffentlicht", dann sollte auch automatisch "In der Navigation anzeigen? = AUS" geschaltet werden.

Hm, bin unsicher. Im Reiter "Seite" sind die beiden Einstellungen ja auch unabhängig voneinander, und ohne weitere Vorkehrungen würde beim Speichern im Pagemanager der Wert überschrieben; oder man dürfte die Checkbox dann nicht umschalten können. Ich denk mal drüber nach.

**Comment by cmb69** [comment]
> Ich denk mal drüber nach.

Ich sehe keine saubere Möglichkeit, das zu lösen. Eigentlich bräuchte der Pagemanager zwei Checkboxen, aber das gibt die API nicht her. (Und noch eigentlicher sollte es gar keine zwei Booleschen Flags geben, sondern eine Aufzählung, da unveröffentlicht immer versteckt impliziert, aber das kann aus Gründen der Abwärtskompatibilität nicht einfach geändert werden.) Ich werd's also so lassen wie es jetzt ist.

Vielleicht schreibt ja jemand mal einen alternativen Pagemanager, der ein anderes Widget verwendet (evtl. [nestedSortable](http://mjsarfatti.com/sandbox/nestedSortable/)), das mehr Flexibilität bietet.
