### ISSUE TITLE
Use same size for fa-buttons

### ISSUE THREAD

**Issue by frase-git** [cmb69/pagemanager_xh#57]
Example
`<span class="fa fa-expand fa-lg fa-fw" aria-hidden="true"></span>`
`fa-fw` makes the button widths identical.
Then you can reduce the paddings and margins.
```
#pagemanager_toolbar button {
	margin: .25em;
	padding: .25em;
}
```

**Comment by cmb69** [comment]
Nice, thanks! However, that clashes with fhs-simple-2019, and I really don't want to add `!important`.

**Comment by frase-git** [comment]
If this proposal (https://cmsimpleforum.com/viewtopic.php?f=29&t=16958) is realized, you will not have to worry about collisions with templates.

**Comment by cmb69** [comment]
Yeah, sure, but I considered this for Pagemanager_XH 3.5, and I don't think it should go into that version. :)

**Comment by cmb69** [comment]
This is actually obsolete due to #73.
