### ISSUE TITLE
Subpages of a sole toplevel page cannot be deleted

### ISSUE THREAD

**Issue by lck-git** [cmb69/pagemanager_xh#60]
For more Info see [CMSimple_XH-Forum](https://cmsimpleforum.com/viewtopic.php?f=16&t=16130&p=75105#p75100).

[Possible solution (tested)](https://cmsimpleforum.com/viewtopic.php?f=16&t=16130&p=75114#p75114).

**Comment by olape-git** [comment]
[does not delete subpages, if only 1x level 1](https://github.com/olape-git/pagemanager_xh/commit/43bb98f14d161179e226e6055e7dbd9a3f4b6e85)

**Comment by cmb69** [comment]
Danke fürs weiterleiten!
