### ISSUE TITLE
Pagemanager 3.6 shows all pages but not all have been selected

### ISSUE THREAD

**Issue by mstfly** [cmb69/pagemanager_xh#76]
Seit dem Update auf die Version 1.7.5 (von 1.7.3) inkl. dem Pagemanager 3.6 habe ich in meinem Menü alle Seiten, die vorhanden sind, aber nicht alle wurden ausgewählt. In der vorherigen Version wurde die nicht ausgewählten Seiten nicht angezeigt. Gibt es hierfür einen Grund, der dieses Verhalten zeigt?

**Comment by cmb69** [comment]
Ich bin nicht sicher, ob ich dich richtig verstehe. Ich vermute es hängt mit der Einstellung `Plugins → Pagemanager → Konfiguration → Pagedata → Attribute` zusammen. Dort kann man zwischen `LEER`, `linked_to_menu` (versteckte Seiten) und `published` (veröffentlichte Seiten) wählen. Das bestimmt, was die Checkboxen unter `Seiten` anzeigen.

**Comment by mstfly** [comment]
Ja, das ist die richtige Stelle, aber leider funktioniert das nicht mehr so. Es gibt zwar immer noch die Attribute LEER, linked_to_menu und published, aber die Bedeutung ist anders. Folgender Hilfetext kommt aktuell:
![Pagemanager_3_6](https://user-images.githubusercontent.com/13704860/174486861-b25a57ac-7613-4b3d-809b-fd61321f9c88.png)

Danach gibt es keine versteckten Seiten mehr, den linked_to_menu ist sichtbar im Menü, obwohl der Hacken in der Checkbox nicht vorhanden ist. Ist das so gewollt oder gibt es jetzt eine andere Funktion für Seiten nicht mehr anzeigen, weil es vielleicht noch nicht veröffentlichtbare Seiten gibt, die in Bearbeitung sind.

**Comment by mstfly** [comment]
Beigefügt ein Beispiel wie es jetzt ist:

1. Seiten verwalten:
![Turniere](https://user-images.githubusercontent.com/13704860/174487155-9f6b7395-9f66-4ef2-8b72-a99fb5aa87ce.png)

2. Anzeige auf der HP:

![Turniere_HP](https://user-images.githubusercontent.com/13704860/174487182-e41c7e1a-a665-4eeb-9cec-8defb4309216.png)

**Comment by mstfly** [comment]
Es sollten aber lediglich die ausgewählten Turnierergebnisse angezeigt werden. Dieses funktioniert jetzt nicht mehr. Wie ist jetzt sinnvoll zu verfahren?

**Comment by cmb69** [comment]
An der Funktionsweise sollte sich nichts geändert haben. Die einzige Änderung, die hier eventuell relevant sein könnte ist, #71, aber ich denke eigentlich nicht, dass das hier wirklich relevant ist.

Ich frage mich aber, ob es überhaupt am Pagemanager liegt, oder ob da vielleicht ein template-spezifisches Menü verwendet wird. Welches Template ist denn im Einsatz?

**Comment by mstfly** [comment]
Ein angepasstes Template names se2015, dass ich vor Jahren erworben und umgestellt habe für die Verwendung mit cmsimple_XH. Bis zur Version cmsimple_xh 1.7.5 und pagemanager 3.6 hat das auch alles einwandfrei funktioniert. Ich will gern checken, ob das Template jetzt irgendetwas auslöst was vorher nicht war.

**Comment by cmb69** [comment]
Vielleicht noch mal alles genau prüfen. Ich habe folgende Pagemanager-Konfiguration:

![Screenshot 2022-06-19 172228](https://user-images.githubusercontent.com/2306138/174488427-b64d7c1c-2d3d-4032-b91d-565e8261b8a6.gif)

Ich habe eine verlinkte Seite `Content`:

![Screenshot 2022-06-19 172447](https://user-images.githubusercontent.com/2306138/174488501-4fe4eb71-efa9-41b1-a215-fd77cf8a0ec9.gif)

Nun gehe ich zu `Seiten`, entferne das Häkchen bei `Content` und speichere:

![Screenshot 2022-06-19 172524](https://user-images.githubusercontent.com/2306138/174488537-93c85468-a69c-42ce-8feb-e565e29248fa.gif)

Dann aktualisiere ich die Seite im Browser (F5), und `Content` ist nicht mehr im Menü:

![Screenshot 2022-06-19 172711](https://user-images.githubusercontent.com/2306138/174488589-e8d797dc-4ef5-408a-9bbe-1101275de114.gif)

Dann wechsle ich in den Bearbeitungsmodus, und wähle die `Content` Seite, und wechsle in den Reiter `Seite`; dort sehe ich, dass das Häkchen bei `In der Navigation anzeigen?` nicht mehr gesetzt ist:

![Screenshot 2022-06-19 172823](https://user-images.githubusercontent.com/2306138/174488653-d1c3a86f-c665-4526-973a-74e456ad86c8.gif)

Und genau darum geht es bei diesen Häkchen; für `linked_to_menu` ist das Häkchen im Pagemanager einfach nur eine Alternative zu `In der Navigation anzeigen?`; für `published` ist es eine Alternative zu `Veröffentlicht?`.

**Comment by cmb69** [comment]
Ich gehe eigentlich nach wie vor davon aus, dass das Problem am Custom-Menu liegt, und schließe das Ticket daher. Falls das doch nicht der Fall ist, bitte Ticket wieder öffnen,.
